---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "clinicalrelevance-api-service"
  namespace: "default"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: "clinicalrelevance-api"
  type: "LoadBalancer"
  loadBalancerIP: ""